# Generated by Django 5.0.4 on 2024-05-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Syndicatecom', '0002_show_delete_sitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='flyers/'),
        ),
    ]
