# Generated by Django 5.0.4 on 2024-05-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Syndicatecom', '0003_show_flyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='address',
            field=models.CharField(default='TBA', max_length=255),
            preserve_default=False,
        ),
    ]
