# Generated by Django 5.0.4 on 2024-05-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Syndicatecom', '0004_show_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='band_members/')),
                ('description', models.TextField()),
            ],
        ),
    ]
