# Generated by Django 5.0.4 on 2024-05-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Syndicatecom', '0005_bandmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BandMember',
        ),
    ]
