# Generated by Django 5.0.3 on 2024-06-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Syndicatecom', '0006_delete_bandmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(upload_to='album_covers/')),
                ('release_date', models.DateField()),
                ('spotify_link', models.URLField(blank=True)),
                ('apple_music_link', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('credits', models.TextField()),
            ],
        ),
    ]
