# Generated by Django 5.0.3 on 2024-06-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Syndicatecom', '0007_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='address',
        ),
        migrations.RemoveField(
            model_name='show',
            name='flyer',
        ),
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='setlist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='ticket_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
