# Generated by Django 5.0.3 on 2024-06-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Syndicatecom', '0008_remove_show_address_remove_show_flyer_show_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='event_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
