# Generated by Django 5.0.3 on 2024-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Syndicatecom', '0011_show_setlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='recorded_at',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='apple_music_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(upload_to='albums'),
        ),
        migrations.AlterField(
            model_name='album',
            name='spotify_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='youtube_link',
            field=models.URLField(),
        ),
    ]
