# Generated by Django 5.0.3 on 2024-06-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Syndicatecom', '0013_galleryimage_delete_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover_url', models.ImageField(upload_to='album_covers/')),
                ('recorded_at', models.CharField(blank=True, max_length=200, null=True)),
                ('credits', models.TextField(blank=True, null=True)),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('apple_music_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
