# Generated by Django 5.0.3 on 2024-06-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Syndicatecom', '0015_album_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='description',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
